-- Registries are executable documentation. Only entries marked implemented may
-- be advertised through CPUID or the compatibility generator.
local M = {}

M.instructions = {
  { name = "ADD", encoding = "01/03/81.0/83.0", status = "implemented", class = "integer" },
  { name = "AND", encoding = "21/23/81.4/83.4", status = "implemented", class = "integer" },
  { name = "CALL", encoding = "E8/FF.2", status = "implemented", class = "control" },
  { name = "CMP", encoding = "39/3B/81.7/83.7", status = "implemented", class = "integer" },
  { name = "CPUID", encoding = "0F A2", status = "implemented", class = "system" },
  { name = "ENDBR64", encoding = "F3 0F 1E FA", status = "implemented", class = "control" },
  { name = "IMUL", encoding = "0F AF/69/6B", status = "implemented", class = "integer" },
  { name = "Jcc", encoding = "70-7F/0F 80-8F", status = "implemented", class = "control" },
  { name = "JMP", encoding = "E9/EB/FF.4", status = "implemented", class = "control" },
  { name = "LEA", encoding = "8D", status = "implemented", class = "integer" },
  { name = "LEAVE", encoding = "C9", status = "implemented", class = "control" },
  { name = "MOV", encoding = "88-8B/B0-BF/C6/C7", status = "implemented", class = "integer" },
  { name = "MOVSX/MOVSXD/MOVZX", encoding = "0F BE/BF/B6/B7/63", status = "implemented", class = "integer" },
  { name = "NOP", encoding = "90/0F 1F", status = "implemented", class = "control" },
  { name = "OR", encoding = "09/0B/81.1/83.1", status = "implemented", class = "integer" },
  { name = "POP", encoding = "58-5F", status = "implemented", class = "stack" },
  { name = "PUSH", encoding = "50-57/68/6A/FF.6", status = "implemented", class = "stack" },
  { name = "RET", encoding = "C3", status = "implemented", class = "control" },
  { name = "SUB", encoding = "29/2B/81.5/83.5", status = "implemented", class = "integer" },
  { name = "SYSCALL", encoding = "0F 05", status = "implemented", class = "system" },
  { name = "TEST", encoding = "85/F7.0", status = "implemented", class = "integer" },
  { name = "XOR", encoding = "31/33/81.6/83.6", status = "implemented", class = "integer" },
  { name = "x87", encoding = "D8-DF", status = "planned", class = "floating-point" },
  { name = "SSE2/SSE3/SSSE3", encoding = "0F maps", status = "planned", class = "vector" },
  { name = "CLMUL/POPCNT/ADX/BMI2", encoding = "0F maps", status = "planned", class = "extended" },
  { name = "privileged instructions", encoding = "system", status = "fault", class = "system" },
}

M.syscalls = {
  { number = 0, name = "read", status = "implemented" },
  { number = 1, name = "write", status = "implemented" },
  { number = 2, name = "open", status = "implemented" },
  { number = 3, name = "close", status = "implemented" },
  { number = 5, name = "fstat", status = "implemented" },
  { number = 8, name = "lseek", status = "implemented" },
  { number = 9, name = "mmap", status = "implemented" },
  { number = 10, name = "mprotect", status = "implemented" },
  { number = 11, name = "munmap", status = "implemented" },
  { number = 12, name = "brk", status = "implemented" },
  { number = 13, name = "rt_sigaction", status = "stubbed" },
  { number = 14, name = "rt_sigprocmask", status = "stubbed" },
  { number = 16, name = "ioctl", status = "stubbed" },
  { number = 17, name = "pread64", status = "implemented" },
  { number = 21, name = "access", status = "implemented" },
  { number = 22, name = "pipe", status = "planned" },
  { number = 32, name = "dup", status = "implemented" },
  { number = 33, name = "dup2", status = "implemented" },
  { number = 39, name = "getpid", status = "implemented" },
  { number = 41, name = "socket", status = "local-only" },
  { number = 53, name = "socketpair", status = "planned" },
  { number = 56, name = "clone", status = "planned" },
  { number = 57, name = "fork", status = "planned" },
  { number = 59, name = "execve", status = "planned" },
  { number = 60, name = "exit", status = "implemented" },
  { number = 61, name = "wait4", status = "planned" },
  { number = 62, name = "kill", status = "planned" },
  { number = 63, name = "uname", status = "implemented" },
  { number = 72, name = "fcntl", status = "stubbed" },
  { number = 79, name = "getcwd", status = "implemented" },
  { number = 89, name = "readlink", status = "implemented" },
  { number = 158, name = "arch_prctl", status = "implemented" },
  { number = 186, name = "gettid", status = "implemented" },
  { number = 202, name = "futex", status = "planned" },
  { number = 218, name = "set_tid_address", status = "implemented" },
  { number = 228, name = "clock_gettime", status = "implemented" },
  { number = 231, name = "exit_group", status = "implemented" },
  { number = 257, name = "openat", status = "implemented" },
  { number = 262, name = "newfstatat", status = "implemented" },
  { number = 273, name = "set_robust_list", status = "implemented" },
  { number = 302, name = "prlimit64", status = "implemented" },
  { number = 318, name = "getrandom", status = "implemented" },
  { number = "other", name = "unknown", status = "ENOSYS" },
  { number = "AF_INET", name = "external networking", status = "EAFNOSUPPORT" },
}

return M

